apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qdrant-gp3
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  fsType: ext4

