apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: agentic-rag
type: Opaque
stringData:
  OPENAI_API_KEY: "__OPENAI_API_KEY__"
  LANGCHAIN_API_KEY: "__LANGCHAIN_API_KEY__"
  COHERE_API_KEY: "__COHERE_API_KEY__"
  BRAVE_API_KEY: "__BRAVE_API_KEY__"
  E2B_API_KEY: "__E2B_API_KEY__"
  TAVILY_API_KEY: "__TAVILY_API_KEY__"
  DATABASE_URL: "__DATABASE_URL__"
  CHECKPOINT_POSTGRES_DATABASE_URL: "__CHECKPOINT_POSTGRES_DATABASE_URL__"
  REDIS_URL: "__REDIS_URL__"
  SERVICE_AUTH_SECRET: "__SERVICE_AUTH_SECRET__"
  SLACK_BOT_TOKEN: "__SLACK_BOT_TOKEN__"
  SLACK_SIGNING_SECRET: "__SLACK_SIGNING_SECRET__"
  SMTP_SERVER: "__SMTP_SERVER__"
  SMTP_PORT: "__SMTP_PORT__"
  SMTP_USER: "__SMTP_USER__"
  SMTP_PASSWORD: "__SMTP_PASSWORD__"
